ucbds-infra/otter-grader

- local_grader/docker.py
Add docker spawning py for integration with other scripts
> Added docker spawning py

- bin/otter
- otter/cli.py
- otter/grade.py
- otter/metadata.py
> Filename mapping

- local_grader/metadata.py
- local_grader/utils.py
- test/sample-metadata/gradescope-export/submission_metadata.yml
- test/test_parsers.py
> finished group submission functionality

- docker/Dockerfile
- otter/cli.py
- otter/grade.py
> added question mapping

- otter/cli.py
- otter/parallel.py
> Parallel docker

- otter/metadata.py
> finished updated GS parser

- README.md
- otter/gs_generator.py
- test/integration/autograder-correct/setup.sh
> Update setup.sh for GS to Python 3.7

- README.md
- otter/grade.py
Adds missing patch of otter.Notebook.export in second execution of source in grade.py
> added missing patch of Notebook.export in grade.py

- README.md
- otter/grade.py
> Fixed issue with relative imports on GS

- README.md
- otter/__init__.py
- update_versions.py
Adds `__version__` as a global variable
> Add package info

- README.md
- otter/gs_generator.py
- test/integration/autograder-correct/run_autograder
> fixed rerunning tests issue

- docs/command-line.md
- docs/gradescope.md
- docs/index.md
- docs/using_otter.md
- otter/__init__.py
- update_versions.py
Add updates to docs from v0.4.3, v0.4.4, v0.4.5, v0.4.6, and v0.4.7
> updated docs and update_versions and otter.__version__

- README.md
- otter/metadata.py
> Fix gradescope parser to handle group submissions

- docs/gradescope.md
> Fix typo in docs

- docker/Dockerfile
- otter/assign.py
- otter/generate.py
- test/test-assign/output-correct/autograder/example.ipynb
- test/test-assign/output-correct/autograder/requirements.txt
- test/test-assign/output-correct/student/example.ipynb
- test/test-generate/autograder-correct/requirements.txt
- update_versions.py
* otter assign removal of empty question cells
* install beta versions in Dockerfile, generate.py, etc.
> Misc. updates to beta

- docs/conf.py
- docs/requirements.txt
In case you're curious - here are the changes needed to demo the book theme on these docs, let me know what you think
> using sphinx book theme

- .travis.yml
- Dockerfile
- README.md
- otter/execute.py
- otter/generate/autograder.py
- otter/notebook.py
- test/__main__.py
- test/test_generate/test-autograder/autograder-correct/requirements.txt
- test/test_generate/test-autograder/autograder-correct/run_autograder
- test/test_generate/test-autograder/results-correct.json
- update_versions.py
Makes changes discussed in #86. Also includes a fix to the log verification so that checks don't overwrite the existing log.
Closes #86
> Additional plaintext rendering for Gradescope

- otter/execute/__init__.py
- otter/execute/execute_notebook.py
> added ignorable cells for execution

- Dockerfile
- otter/argparser.py
- otter/execute/results.py
- otter/generate/templates/requirements.txt
- otter/version.py
- test/test-assign/gs-autograder-correct/requirements.txt
- test/test-assign/rmd-autograder-correct/requirements.txt
- test/test_generate/test-autograder/autograder-correct/requirements.txt
- test/test_generate/test-run-autograder/autograder-correct/source/requirements.txt
> Fix zero division error in grading

- docs/changelog.md
- otter/argparser.py
- otter/assign/__init__.py
- otter/assign/utils.py
- otter/generate/autograder.py
> Added username, password flags

- docs/changelog.md
- otter/execute/__init__.py
- otter/export/exporters/via_html.py
- otter/export/exporters/via_latex.py
- otter/run/run_autograder/r_adapter/run_autograder.py
- otter/run/run_autograder/run_autograder.py
- otter/run/run_autograder/utils.py
- otter/test_files/ok_test.py
- test/test-run/autograder/source/otter_config.json
- test/test_run.py
> Added support for .py files

- docs/changelog.md
- otter/assign/output.py
- otter/assign/solutions.py
- otter/run/run_autograder/run_autograder.py
- otter/test_files/__init__.py
- test/test-assign/example.ipynb
> Updates to assign, log, plugins

- docs/changelog.md
- otter/run/run_autograder/__init__.py
> Print all dataframe rows per #224

- docs/changelog.md
- docs/otter_assign/python_notebook_format.md
- otter/assign/assignment.py
- otter/plugins/__init__.py
- otter/run/run_autograder/__init__.py
- otter/run/run_autograder/constants.py
- otter/run/run_autograder/run_autograder.py
- otter/utils.py
- test/test-assign/example.ipynb
- test/test-assign/generate-gradescope.ipynb
> Added total score printout

- otter/check/notebook.py
- requirements-test.txt
- requirements.txt
- test/test-run/autograder/source/run_otter.py
- test/test_generate/test_token.py
- test/test_grade.py
- test/test_run.py
> Remove unneeded requirements

- docs/changelog.md
- otter/assign/utils.py
- otter/test_files/__init__.py
> Display failed tests in Otter Assign more nicely

- CHANGELOG.md
- otter/assign/assignment.py
- otter/assign/cell_generators.py
- otter/assign/notebook_transformer.py
- otter/assign/utils.py
- otter/check/notebook.py
- otter/check/utils.py
- otter/check/validate_export/__init__.py
- otter/check/validate_export/__main__.py
- otter/test_files/__init__.py
> Validate submission zip against local test cases

- docs/changelog.md
- requirements-test.txt
- requirements.txt
> Remove `rpy2` as a required dependency

- environment.yml
- otter/assign/utils.py
- otter/generate/templates/python/environment.yml
- otter/generate/templates/r/environment.yml
- otter/generate/templates/r/requirements.r
- test/test-assign/gs-autograder-correct/environment.yml
- test/test-assign/rmd-autograder-correct/environment.yml
- test/test-assign/rmd-autograder-correct/requirements.r
- test/test-run/autograder/source/environment.yml
- test/test_generate/test-autograder/autograder-correct/environment.yml
- test/test_generate/test-autograder/autograder-token-correct/environment.yml
> Fix issues in Gradescope build due to stringi

- CHANGELOG.md
- docs/otter_assign/python_notebook_format.rst
- otter/assign/notebook_transformer.py
- test/test-assign/generate-otter.ipynb
- test/test-assign/otter-correct/autograder/generate-otter.ipynb
- test/test-assign/otter-correct/student/generate-otter.ipynb
> Added a question metadata key making check cells optional in Otter Assign

- Dockerfile
- docs/changelog.md
- otter/generate/templates/python/requirements.txt
- otter/generate/templates/r/requirements.txt
- otter/run/__init__.py
- otter/run/run_autograder/__init__.py
- otter/run/run_autograder/run_autograder.py
- otter/run/run_autograder/utils.py
- test/test-assign/gs-autograder-correct/requirements.txt
- test/test-assign/rmd-autograder-correct/requirements.txt
- test/test-run/autograder/source/requirements.txt
- test/test_generate/test-autograder/autograder-correct/requirements.txt
- test/test_generate/test-autograder/autograder-custom-env/requirements.txt
> Student-visible error reporting on Gradescope

- CHANGELOG.md
- otter/check/notebook.py
- otter/check/utils.py
- otter/execute/execute_notebook.py
- test/test_logs.py
- test/test_notebook.py
> Add support for Google Colab to `otter.Notebook`

- CHANGELOG.md
- otter/check/notebook.py
- otter/check/utils.py
- otter/test_files/__init__.py
- test/test_notebook.py
> Logging and `check_all` updates for `Notebook`

- CITATION.cff
- release.py
> Add CITATION.cff

- CHANGELOG.md
- otter/api.py
- otter/run/__init__.py
> Make otter run accept zip files

- CHANGELOG.md
- docs/otter_assign/index.rst
- otter/assign/v0/convert/__init__.py
- otter/assign/v0/convert/__main__.py
- otter/assign/v0/convert/notebook_transformer.py
> Added Assign format converter

- docs/_static/notebooks/assign-code-question-v1.ipynb
- docs/_static/notebooks/assign-code-question.ipynb
- docs/_static/notebooks/assign-r-code-question-v1.ipynb
- docs/_static/notebooks/assign-r-code-question.ipynb
- docs/index.rst
- docs/otter_assign/v0/r_notebook_format.rst
- docs/otter_assign/v0/rmd_format.rst
- docs/otter_assign/v1/notebook_format.rst
- docs/otter_assign/v1/rmd_format.rst
- otter/assign/constants.py
- test/test-assign/r-example.ipynb
> Documentation updates

- .github/workflows/run-tests.yml
I've simulated a failing test in https://github.com/fritterhoff/otter-grader/commit/70885f921ad0a3316a9a372a530b643fbef485d5 - that's now detected correct...
> Detect failing tests in docker

- CHANGELOG.md
- Dockerfile
- otter/generate/__init__.py
- otter/generate/templates/python/requirements.txt
- otter/generate/templates/r/requirements.txt
- otter/run/run_autograder/runners/r_runner.py
- otter/run/run_autograder/utils.py
- otter/utils.py
- test/test-assign/gs-autograder-correct/requirements.txt
- test/test-assign/rmd-autograder-correct/requirements.txt
- test/test-assign/rmd-autograder-correct/setup.sh
- test/test-run/autograder/source/requirements.txt
- test/test_generate/test-autograder/autograder-correct/requirements.txt
- test/test_generate/test-autograder/autograder-custom-env/requirements.txt
- test/test_generate/test-autograder/autograder-token-correct/requirements.txt
Fixes an issue described in the [Otter Slack](https://otter-grader.slack.com/archives/CT9QJK4PL/p1630634808054500).
> Remove cells with syntax errors in R notebooks

- otter/generate/__init__.py
> Remove "empty" tokens in Otter Generate

- CHANGELOG.md
- Dockerfile
- otter/check/notebook.py
- otter/generate/__init__.py
- otter/generate/templates/python/requirements.txt
- otter/generate/templates/r/requirements.txt
- otter/plugins/builtin/grade_override.py
- otter/run/run_autograder/__init__.py
- otter/run/run_autograder/runners/python_runner.py
- otter/run/run_autograder/runners/r_runner.py
- otter/test_files/metadata_test.py
- test/test-assign/gs-autograder-correct/requirements.txt
- test/test-assign/rmd-autograder-correct/requirements.txt
- test/test-run/autograder/source/requirements.txt
- test/test_generate/test-autograder/autograder-correct/requirements.txt
- test/test_generate/test-autograder/autograder-custom-env/requirements.txt
- test/test_generate/test-autograder/autograder-token-correct/requirements.txt
> Specify encoding for JSON loads

- CHANGELOG.md
- Dockerfile
- otter/generate/templates/python/requirements.txt
- otter/generate/templates/r/requirements.txt
- otter/grade/containers.py
- test/test-assign/gs-autograder-correct/requirements.txt
- test/test-assign/rmd-autograder-correct/requirements.txt
- test/test-run/autograder/source/requirements.txt
- test/test_generate/test-autograder/autograder-correct/requirements.txt
- test/test_generate/test-autograder/autograder-custom-env/requirements.txt
- test/test_generate/test-autograder/autograder-token-correct/requirements.txt
> Close file handles in Otter Grade

- CHANGELOG.md
- Dockerfile
- otter/generate/templates/python/requirements.txt
- otter/generate/templates/r/requirements.txt
- otter/generate/templates/r/setup.sh
- otter/grade/containers.py
- test/test-assign/gs-autograder-correct/requirements.txt
- test/test-assign/rmd-autograder-correct/requirements.txt
- test/test-assign/rmd-autograder-correct/setup.sh
- test/test-run/autograder/source/requirements.txt
- test/test_generate/test-autograder/autograder-correct/requirements.txt
- test/test_generate/test-autograder/autograder-custom-env/requirements.txt
- test/test_generate/test-autograder/autograder-token-correct/requirements.txt
Also includes some commits from #391, so that should be merged first.
Closes #386
> Set Conda `channel_priority` to `strict` in R `setup.sh` files

- CHANGELOG.md
- docs/otter_check/dot_otter_files.rst
- docs/workflow/executing_submissions/otter_grade.rst
- docs/workflow/otter_generate/container_image.rst
- otter/cli.py
- otter/grade/__init__.py
- otter/grade/containers.py
- otter/run/run_autograder/__init__.py
- otter/run/run_autograder/runners/python_runner.py
Allows the user the specify the submission extension for `otter grade`. Also brings support for grading zip files to R assignments.
Closes #386
> Accepting extensions for Otter Grade

- CHANGELOG.md
- otter/assign/notebook_transformer.py
- otter/assign/utils.py
> Added question name to `AssignNotebookFormatException`s

- CHANGELOG.md
- otter/assign/tests.py
- otter/check/notebook.py
> Allow zip exports when PDF generation fails

- otter/test_files/abstract_test.py
> Put instructor-provided messages before test case errors

- CHANGELOG.md
- otter/assign/tests.py
- test/test_assign.py
> Round point values for display in Otter Assign

- CHANGELOG.md
- otter/grade/Dockerfile
> Remove testing line from otter grade dockerfile

- CHANGELOG.md
- otter/export/exporters/__init__.py
> Only import HTML exporter when it's needed

- docs/workflow/otter_generate/index.rst
got a little mixed up here, so wanted to clarify to help others.
> add clarification of how to setup autosubmission

- .gitignore
- CHANGELOG.md
- environment.yml
- otter/generate/templates/python/setup.sh
- otter/generate/templates/r/environment.yml
- otter/generate/templates/r/setup.sh
- test/test-assign/example-autograder-correct/setup.sh
- test/test-assign/gs-autograder-correct/setup.sh
- test/test-assign/rmd-autograder-correct/environment.yml
- test/test-assign/rmd-autograder-correct/setup.sh
- test/test-run/autograder/source/setup.sh
- test/test_generate/test-autograder/autograder-correct/setup.sh
- test/test_generate/test-autograder/autograder-custom-env/setup.sh
- test/test_generate/test-autograder/autograder-r-correct/environment.yml
- test/test_generate/test-autograder/autograder-r-correct/setup.sh
- test/test_generate/test-autograder/autograder-token-correct/setup.sh
> Update setup.sh packages and r-base version

- CHANGELOG.md
- otter/test_files/__init__.py
- test/test-run/autograder/source/tests/q4.py
> Round results point values to 5 decimal places

- docs/otter_assign/v1/notebook_format.rst
- docs/workflow/otter_generate/index.rst
This was confusing to me until I read through the issues so trying to clarify a bit here.
> Clarify the gradescope token requirements in the docs

- CHANGELOG.md
- docs/otter_assign/v1/notebook_format.rst
- environment.yml
- otter/assign/assignment.py
- otter/assign/notebook_transformer.py
- test/test-assign/assignment_config.yml
- test/test-assign/exception-example.ipynb
> Add configuration files for Otter Assign

- otter/grade/containers.py
These (simple) changes make it possible to run the docker grading container on a remote host.
> Add support for working with a remote docker host

- CHANGELOG.md
- otter/grade/containers.py
- otter/grade/utils.py
- test/test_grade.py
> changing base image changes image tag

- CHANGELOG.md
- otter/generate/templates/python/requirements.txt
- otter/generate/templates/r/requirements.txt
- otter/plugins/builtin/gmail_notifications/__init__.py
- otter/plugins/builtin/grade_override.py
- requirements-test.txt
- requirements.txt
- test/test-assign/example-autograder-correct/requirements.txt
- test/test-assign/gs-autograder-correct/requirements.txt
- test/test-assign/rmd-autograder-correct/requirements.txt
- test/test-run/autograder/source/requirements.txt
- test/test_generate/test-autograder/autograder-correct/requirements.txt
- test/test_generate/test-autograder/autograder-custom-env/requirements.txt
- test/test_generate/test-autograder/autograder-r-correct/requirements.txt
- test/test_generate/test-autograder/autograder-token-correct/requirements.txt
> make gspread optional dependency

- otter/test_files/__init__.py
> Correctly handle test file points for #563

- CHANGELOG.md
- otter/assign/solutions.py
> Support dictionary and tuple assignments in otter assign

- CHANGELOG.md
- otter/assign/r_adapter/cell_factory.py
- test/test-assign/r-example.ipynb
- test/test-assign/rmd-correct/autograder/rmd-example.Rmd
- test/test-assign/rmd-correct/student/rmd-example.Rmd
> Add pdf arg to ottr::export

- .github/workflows/run-tests.yml
- requirements-test.txt
https://about.codecov.io/blog/message-regarding-the-pypi-package/
> Use codecov action to upload coverage

- .github/workflows/run-tests.yml
- CHANGELOG.md
- Makefile
- otter/assign/solutions.py
> Replace slow regex with more performant version

- CHANGELOG.md
- otter/assign/tests_manager.py
- otter/test_files/abstract_test.py
- test/test_assign.py
> Add question name to point value validation errors

- otter/grade/containers.py
https://stackoverflow.com/questions/76477878/python-on-whales-exceptions-dockerexception-the-process-cannot-access-the?newreg=1a8d8004e709427d8ec7623748cc8b8d
> Close file handles before docker cp

- CHANGELOG.md
- otter/cli.py
- otter/grade/__init__.py
- otter/grade/containers.py
- test/conftest.py
- test/test_grade/test_integration.py
> Use Otter Grade CLI to override otter_config.json values

- CHANGELOG.md
- otter/assign/notebook_transformer.py
> Normalize notebooks before write in Otter Assign

- CHANGELOG.md
- otter/assign/output.py
- otter/assign/tests_manager.py
> Added assignment summary to Otter Assign

- CHANGELOG.md
- Dockerfile
- bin/run_tests
- otter/generate/__init__.py
- otter/generate/templates/common/run_autograder
- otter/generate/templates/python/setup.sh
- otter/generate/templates/r/setup.sh
- otter/run/run_autograder/autograder_config.py
- test/files/Dockerfile
- test/test_assign/files/example-autograder-correct/run_autograder
- test/test_assign/files/example-autograder-correct/setup.sh
- test/test_assign/files/gs-autograder-correct/run_autograder
- test/test_assign/files/gs-autograder-correct/setup.sh
- test/test_assign/files/rmd-autograder-correct/run_autograder
- test/test_assign/files/rmd-autograder-correct/setup.sh
- test/test_generate/files/autograder-correct/run_autograder
- test/test_generate/files/autograder-correct/setup.sh
- test/test_generate/files/autograder-custom-env/run_autograder
- test/test_generate/files/autograder-custom-env/setup.sh
- test/test_generate/files/autograder-r-correct/run_autograder
- test/test_generate/files/autograder-r-correct/setup.sh
- test/test_generate/files/autograder-r-requirements-correct/run_autograder
- test/test_generate/files/autograder-r-requirements-correct/setup.sh
- test/test_generate/files/autograder-token-correct/run_autograder
- test/test_generate/files/autograder-token-correct/setup.sh
- test/test_grade/test_integration.py
- test/test_run/files/autograder/source/run_autograder
- test/test_run/files/autograder/source/setup.sh
> Convert from Conda to Mamba

- CHANGELOG.md
- otter/check/validate_export/__main__.py
> Fix local submission zip check

- CHANGELOG.md
- otter/assign/notebook_transformer.py
- otter/assign/utils.py
- test/utils.py
> Remove cell ID patch from otter assign

- .github/workflows/release.yml
- .github/workflows/run-tests.yml
> Switch from stable branch to latest tag

- .github/workflows/run-tests.yml
See [this comment](https://github.com/mamba-org/setup-micromamba/issues/113#issuecomment-1657280302)
> Add hashes of requirements files to mamba env cache key

- .coveragerc
- CHANGELOG.md
- otter/assign/utils.py
- otter/execute/__init__.py
- otter/execute/logging.py
- otter/execute/preprocessor.py
- otter/run/__init__.py
- otter/run/run_autograder/__init__.py
- otter/run/run_autograder/runners/abstract_runner.py
- otter/run/run_autograder/runners/python_runner.py
- otter/run/run_autograder/utils.py
- otter/test_files/__init__.py
- otter/utils.py
> Add a simple TCP socket server for receiving Otter's logs from the executed notebook

- otter/grade/Dockerfile
The build was stopping without this line waiting
for the user to choose their region
> Ubuntu Noninteractive

- CHANGELOG.md
- otter/check/utils.py
This PR fixes #686. This is a duplicate of #687, but this PR merges into the `beta` branch and updates `CHANGELOG.md`, as requested by @chrispyles.
> Fix #686 (Grader Export Cell Fails)

- CHANGELOG.md
- otter/run/run_autograder/runners/abstract_runner.py
> Add default value for users from submission metadata

- CHANGELOG.md
- otter/assign/notebook_transformer.py
- otter/assign/utils.py
> Add remove cell ID patch back to otter assign

- CHANGELOG.md
- otter/check/notebook.py
> Fix download link

- CHANGELOG.md
- otter/execute/__init__.py
> Prevent missing nbconvert from preventing otter package import

- CHANGELOG.md
- otter/test_files/exception_test.py
- otter/test_files/metadata_test.py
- otter/test_files/ok_test.py
> fix no from_string on ok test file

- CHANGELOG.md
- otter/check/notebook.py
> Fix AttributeError in Notebook.check_all

- CHANGELOG.md
- otter/assign/tests_manager.py
> Throw error in otter assign for invalid test cell code

- CHANGELOG.md
- docs/_static/python_setup.sh
- docs/_static/r_setup.sh
- otter/generate/templates/python/setup.sh
- otter/generate/templates/r/setup.sh
- test/test_assign/files/example-autograder-correct/setup.sh
- test/test_assign/files/gs-autograder-correct/setup.sh
- test/test_assign/files/rmd-autograder-correct/setup.sh
- test/test_generate/files/autograder-correct/setup.sh
- test/test_generate/files/autograder-custom-env/setup.sh
- test/test_generate/files/autograder-r-correct/setup.sh
- test/test_generate/files/autograder-r-requirements-correct/setup.sh
- test/test_generate/files/autograder-token-correct/setup.sh
- test/test_run/files/autograder/source/setup.sh
> Pin pandoc to v3.1.11.1

- CHANGELOG.md
- otter/check/validate_export/__main__.py
> Suppress warnings in otter.check.validate_export.__main__

- CHANGELOG.md
- docs/_static/grading-environment-r.yml
- docs/_static/grading-environment.yml
- docs/index.rst
- docs/pdfs.rst
- otter/assign/__init__.py
- otter/export/__init__.py
- otter/export/exporters/__init__.py
- otter/export/exporters/utils.py
- otter/export/exporters/via_html.py
- otter/export/exporters/via_latex.py
- otter/export/utils.py
- otter/generate/__init__.py
- otter/run/run_autograder/utils.py
- requirements-export.txt
>  Convert PDF via HTML exporter to nbconvert WebPDF exporter

- CHANGELOG.md
- otter/generate/__init__.py
- otter/generate/templates/python/setup.sh
- otter/generate/templates/r/setup.sh
- otter/run/run_autograder/autograder_config.py
- otter/run/run_autograder/runners/python_runner.py
- otter/run/run_autograder/runners/r_runner.py
- test/test_assign/files/example-autograder-correct/environment.yml
- test/test_assign/files/example-autograder-correct/setup.sh
- test/test_assign/files/gs-autograder-correct/environment.yml
- test/test_assign/files/gs-autograder-correct/setup.sh
- test/test_assign/files/rmd-autograder-correct/environment.yml
- test/test_assign/files/rmd-autograder-correct/setup.sh
- test/test_generate/files/autograder-correct/environment.yml
- test/test_generate/files/autograder-correct/setup.sh
- test/test_generate/files/autograder-custom-env/environment.yml
- test/test_generate/files/autograder-custom-env/setup.sh
- test/test_generate/files/autograder-r-correct/environment.yml
- test/test_generate/files/autograder-r-correct/setup.sh
- test/test_generate/files/autograder-r-requirements-correct/environment.yml
- test/test_generate/files/autograder-r-requirements-correct/setup.sh
- test/test_generate/files/autograder-token-correct/environment.yml
- test/test_generate/files/autograder-token-correct/setup.sh
- test/test_run/test_integration.py
> Allow PDF via HTML exports in grading containers

- CHANGELOG.md
- otter/assign/assignment.py
- otter/assign/utils.py
- otter/cli.py
- otter/generate/__init__.py
- test/test_assign/files/example-autograder-correct/environment.yml
- test/test_assign/files/example.ipynb
> Add exclude_conda_defaults to otter assign and otter generate

- CHANGELOG.md
- otter/grade/containers.py
- otter/grade/utils.py
- test/test_grade/test_integration.py
- notebook name used as final name
- sorted by notebook name
> Update Otter Grade to sort output CSV by notebook name

- CHANGELOG.md
- otter/generate/__init__.py
- test/test_assign/files/rmd-autograder-correct/environment.yml
- test/test_generate/files/autograder-r-correct/environment.yml
- test/test_generate/files/autograder-r-requirements-correct/environment.yml
> Add gcc_linux-64 and gxx_linux-64 to R grading image dependencies

- CHANGELOG.md
- otter/execute/preprocessor.py
- otter/generate/__init__.py
- test/test_assign/files/rmd-autograder-correct/environment.yml
- test/test_generate/files/autograder-r-correct/environment.yml
- test/test_generate/files/autograder-r-requirements-correct/environment.yml
> Use random variable name for loop variable in grading export cell generated code

- CHANGELOG.md
- otter/cli.py
- test/test_cli.py
> Add --pickle-results option to otter run

- CHANGELOG.md
- requirements.txt
> Add setuptools to required dependencies

- CHANGELOG.md
- otter/cli.py
- otter/grade/__init__.py
- otter/grade/containers.py
- otter/utils.py
- test/test_grade/files/queue/passall_messages.txt
- test/test_grade/test_integration.py
- When an instance of ``multiprocessing.Queue`` is passed to grade/__init_.py::main, progress messages are written to the ``multiprocessing.Queue`
Closes #827
> Otter Grade: Added Progress Monitoring

- CHANGELOG.md
- otter/assign/cell_factory.py
- test/test_assign/files/gs-correct/autograder/generate-gradescope.ipynb
- test/test_assign/files/gs-correct/student/generate-gradescope.ipynb
> Add pip install cell to Colab notebooks

- CHANGELOG.md
- otter/assign/assignment.py
- otter/assign/cell_factory.py
- otter/check/notebook.py
- test/test_assign/files/example-correct/autograder/example.ipynb
- test/test_assign/files/example-correct/student/example.ipynb
- test/test_assign/files/example.ipynb
- test/test_check/test_notebook.py
> Add ability to ignore .OTTER_LOG to Notebook.export and Otter Assign

- CHANGELOG.md
- otter/assign/question_config.py
- otter/assign/r_adapter/tests_manager.py
- otter/assign/tests_manager.py
- otter/test_files/abstract_test.py
- otter/test_files/exception_test.py
- otter/test_files/ok_test.py
- test/test_assign/files/example-autograder-correct/tests/q1.py
- test/test_assign/files/example-correct/autograder/example.ipynb
- test/test_assign/files/example-correct/student/example.ipynb
- test/test_assign/files/example.ipynb
- test/test_assign/files/exception-correct/autograder/tests/q1.py
- test/test_assign/files/exception-correct/student/tests/q1.py
- test/test_assign/files/exception-example.ipynb
- test/test_check/test_notebook.py
- test/test_execute/files/expected_log_results.json
- test/test_test_files/test_exception_test.py
- test/test_test_files/test_ok_test.py
> Fix/add support for all_or_nothing test file config

- CHANGELOG.md
- otter/check/utils.py
- otter/export/exporters/via_html.py
- otter/export/exporters/via_latex.py
- poetry.lock
- pyproject.toml
> Fix jupyterlite install errors

- CHANGELOG.md
- otter/assign/notebook_transformer.py
- otter/assign/output.py
- otter/assign/solutions.py
- otter/assign/utils.py
> Handle invalid kernelspec in otter assign
