ucbds-infra/otter-grader

otter/gofer.py
The CheckCallWrapper currently only handles "naked" calls to check of the form `check()`, and not any calls that take the form `xxx.check()`, such as `grader.check()`. This changes the `visit_Call` function so that it properly handles situations where `check` is inside `node.func.attr` instead of `node.func.id`
=> fix the NodeTransformer not handling notebook.check()

otter/assign/output.py
When no language is specified, a KeyError is thrown, but the code expects an IndexError
=> Fixing bug when no language is specified

docs/changelog.md, otter/generate/templates/environment.yml
The conda environment.yml file pulls in the pip requirements.txt file to install many requirements including otter itself.
On a recent version of gradescope (used on 12 Jan 2021) this failed to install any of the pip packages from the requirements file.
Adding the “file:” designation corrects this.
=> Add missing file specifier in environment template

.github/workflows/run-tests.yml, environment.yml, otter/generate/autograder.py, otter/generate/templates/python/environment.yml, otter/generate/templates/r/environment.yml, test/test-assign/gs-autograder-correct/environment.yml, test/test-assign/gs-autograder-correct/setup.sh, test/test-assign/rmd-autograder-correct/environment.yml, test/test-assign/rmd-autograder-correct/setup.sh, test/test-run/autograder/source/environment.yml, test/test-run/autograder/source/setup.sh, test/test_generate/test-autograder/autograder-correct/environment.yml, test/test_generate/test-autograder/autograder-correct/setup.sh, test/test_generate/test-autograder/autograder-custom-env/environment.yml, test/test_generate/test-autograder/autograder-custom-env/setup.sh, test/test_generate/test-autograder/environment.yml
Updates the conda version to 4.10.3 and removes the unsupported `file:` prefix in environment.yml files.
Closes #272
Alternative to #273
=> Update conda to 4.10.3 and fix conda build

otter/generate/templates/python/environment.yml
This minor fix removes the currently unsupported prepended "file:"
attribute to the pip configuration in environment.yml.
Fix to issue #272
=> Fix to pip config in conda env

CHANGELOG.md, otter/generate/templates/r/environment.yml, test/test-assign/rmd-autograder-correct/environment.yml
Fixes an issue brought up in the [Slack](https://otter-grader.slack.com/archives/CT9QJK4PL/p1630826900072900)
=> Add `libgomp` to environment.yml for R

CHANGELOG.md, otter/grade/containers.py
In some complex setups the load flag must be enabled. It should not cause any problems on more simple setups.
=> Enable loading of docker build

CHANGELOG.md, Dockerfile, otter/generate/templates/python/setup.sh, otter/generate/templates/r/setup.sh, test/test-assign/gs-autograder-correct/setup.sh, test/test-assign/rmd-autograder-correct/setup.sh, test/test_generate/test-autograder/autograder-correct/setup.sh, test/test_generate/test-autograder/autograder-custom-env/setup.sh, test/test_generate/test-autograder/autograder-token-correct/setup.sh
Fixes a bug in the Gradescope image build by using the `texlive-lang-chinese` package instead of manually installing the fandol font.
=> Switch to `texlive-lang-chinese`

docs/otter_assign/v1/notebook_format.rst, otter/assign/assignment.py
Per one of the follow-ups to #129
=> Added the list format of the `requirements` config to the documentation for Otter Assign

otter/check/utils.py
Am helping debug issues where notebooks are not being
saved properly, and I'm not sure if `f.seek(0)` without
re-opening will always work correctly on NFS. Since we're
expecting another process (notebook server) to write to the
file, it's cleaner to just re-open the file each time we
want to test.
=> Re-open file explicitly when checking if notebook has saved

docs/workflow/executing_submissions/otter_run.rst
Not sure if these docs are automatically generated from elsewhere but:
grade_submission argument order was wrong -> grade_submission(student_submission_path, autograder_zip_path) rather than the reverse.
=> Fix "Grading Programmatically" example

docs/tutorial.rst, docs/workflow/executing_submissions/otter_grade.rst, otter/cli.py, otter/grade/__init__.py, otter/grade/containers.py, test/test_grade.py
This PR derives from the [PR](https://github.com/ucbds-infra/otter-grader/pull/487) I submitted on the master branch before I knew about the beta branch!  
- I added a pytest to verify single notebook grading
- made single notebook grading possible for all types of notebooks
- used the instance state of the scores field(GradingResults object) to calculate the percentage correct
=> Single Notebook Containerized Grading

CHANGELOG.md, otter/generate/templates/r/setup.sh, test/test-assign/rmd-autograder-correct/setup.sh, test/test_generate/test-autograder/autograder-r-correct/setup.sh
Fixes a bug brought up in the Otter Slack: https://otter-grader.slack.com/archives/CT9QJK4PL/p1650581556482799?thread_ts=1649792498.203629&cid=CT9QJK4PL
=> Add libmagick++-dev to Gradescope R image

CHANGELOG.md, Dockerfile, otter/check/utils.py, otter/generate/templates/python/requirements.txt, otter/generate/templates/r/requirements.txt, test/test-assign/example-autograder-correct/requirements.txt, test/test-assign/gs-autograder-correct/requirements.txt, test/test-assign/rmd-autograder-correct/requirements.txt, test/test-run/autograder/source/requirements.txt, test/test_generate/test-autograder/autograder-correct/requirements.txt, test/test_generate/test-autograder/autograder-custom-env/requirements.txt, test/test_generate/test-autograder/autograder-r-correct/requirements.txt, test/test_generate/test-autograder/autograder-token-correct/requirements.txt
Fixes a bug from [Slack](https://otter-grader.slack.com/archives/CT9QJK4PL/p1661892005654379) similar to #389.
> We are running into PermissionError when we try to run the student version of the notebook file only on Windows platform. The same notebook file is working on MAC platform. Can you please tell us what we are missing here? I have attached a zip file of the entire directory, including the master notebook file and the student directory with the error.<br><br>
Error details:
```
Running your submission against local test cases...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File ~\anaconda3\lib\site-packages\otter\check\utils.py:78, in grade_zip_file(zip_path, nb_arcname, …
```
=> Close file handles in otter check zip validation

CHANGELOG.md, otter/run/run_autograder/autograder_config.py, otter/test_files/__init__.py, test/test_run.py
=> Add `force_public_test_summary` and make failed public tests display correctly

requirements.txt
otter-grader will fail to import without it, see
https://github.com/conda-forge/staged-recipes/pull/20953#issuecomment-1301101460
=> Add ipython as an explicit requirement

docs/workflow/executing_submissions/gradescope.rst
I believe this should be "hidden test". It doesn't make sense to say "If a student fails a hidden test but no public tests [...] even though the student failed a public test."
=> fix typo in gradescope instructions

otter/plugins/builtin/grade_override.py
In the case where the plugins are stored on the assignment and not in otter_config, we need to set
otter_config["plugins"] with the plugins attribute from the assignment.
=> GradeOverride Plugin

otter/plugins/builtin/grade_override.py
Reverts ucbds-infra/otter-grader#650
@sean-morris reverting this change since I think this is not where we want to be fixing this bug.
=> Revert "GradeOverride Plugin"

CHANGELOG.md, otter/check/notebook.py, test/test_check/test_notebook.py
=> Fix recursive inclusion of files when a directory is in the list passed to the `files` argument of `Notebook.export`

CHANGELOG.md, otter/test_files/exception_test.py
Previously, otter would fail due to PicklingError for exception style tests. This gets rid of test_func from the pickling state because it cannot be pickled.
Fixes https://github.com/ucbds-infra/otter-grader/issues/696.
This is a copy of #698 off of master instead of beta.
=>  Adds __getstate__ to test_case for exception_tests

CHANGELOG.md, otter/execute/__init__.py, otter/test_files/__init__.py, test/test_execute/test_integration.py, test/test_test_files/test_grading_results.py
=> Prevent catastrophic failures from erroring out the autograder

CHANGELOG.md, otter/check/logs.py, otter/execute/__init__.py, otter/execute/logging.py, otter/execute/preprocessor.py, otter/run/run_autograder/__init__.py, otter/test_files/__init__.py, otter/utils.py
See https://github.com/ucbds-infra/otter-grader/issues/723#issuecomment-1710689536
FYI @ctnelson1997 this fix will be included in v5.1.4
=> Use tempfile.mkstemp instead of tempfile.NamedTemporaryFile for windows compatibility

docs/_static/grading-environment-r.yml, docs/_static/r_setup.sh, docs/debugging.rst, docs/index.rst, docs/workflow/executing_submissions/otter_grade.rst, otter/check/logs.py
=> Add submission debugging guide

CHANGELOG.md, otter/execute/preprocessor.py
=> Prevent intercell seeding code from being added to cells using cell magic

CHANGELOG.md, otter/run/run_autograder/autograder_config.py, otter/run/run_autograder/runners/abstract_runner.py, test/test_check/test_notebook.py, test/test_run/files/autograder/source/otter_config.json, test/test_run/files/autograder/submission_metadata.json, test/test_run/test_integration.py, test/utils.py
=> Allow upload of submission PDF

Makefile, test/test_check/files/logs-tests/q4.py, test/test_generate/files/autograder-correct/tests/q4.py, test/test_generate/files/autograder-custom-env/tests/q4.py, test/test_generate/files/autograder-token-correct/tests/q4.py, test/test_generate/files/tests/q4.py, test/test_grade/files/tests/q4.py, test/test_run/files/autograder/source/tests/q4.py
numpy v2.0.0 started causing test cases that passed previously to start failing with
```
❌ Test case failed
Trying:
np.isclose(x, 39.0625)
Expecting:
True
**********************************************************************
Line 2, in q4 0
Failed example:
np.isclose(x, 39.0625)
Expected:
True
Got:
np.True_
```
=> Fix tests using np.isclose due to new numpy bool dtype

CHANGELOG.md, otter/grade/Dockerfile
- wget added to Dockerfile for backwards compatibility with autograder.zip files generated with otter-grader version 4
=> Otter Grade Dockerfile Added wget

CHANGELOG.md, otter/grade/__init__.py, otter/grade/containers.py, otter/grade/utils.py, test/test_grade/test_integration.py
This allows notebooks to timeout but not kill the entire otter grade process. 
final_grades.csv now records the status of the notebook in terms of grading completion as a column. 
If a notebook times out this is indicated while notebooks that have not timed out will record their scores.
Closes #813
=> Otter Grade Timeout Updated

CHANGELOG.md, otter/cli.py, otter/grade/__init__.py, test/test_cli.py, test/test_grade/files/results/fails1.txt, test/test_grade/files/results/fails1H.txt, test/test_grade/files/results/fails1and3and6.txt, test/test_grade/files/results/fails1and4.txt, test/test_grade/files/results/fails2.txt, test/test_grade/files/results/fails2and3and6H.txt, test/test_grade/files/results/fails2and4.txt, test/test_grade/files/results/fails2and6H.txt, test/test_grade/files/results/fails3.txt, test/test_grade/files/results/fails3and4.txt, test/test_grade/files/results/fails4.txt, test/test_grade/files/results/fails6.txt, test/test_grade/files/results/fails6H.txt, test/test_grade/files/results/passesAll.txt, test/test_grade/test_integration.py
Addresses Issue #814: Otter Grade: Write out Individual Results as well as final_grades.csv
=> Otter Grade Write Individual Notebook Results

CHANGELOG.md, otter/assign/utils.py
=> Fix converting indented functions in test cells to doctests

CHANGELOG.md, otter/generate/templates/common/run_otter.py, test/test_assign/files/example-autograder-correct/run_otter.py, test/test_assign/files/gs-autograder-correct/run_otter.py, test/test_assign/files/rmd-autograder-correct/run_otter.py, test/test_generate/files/autograder-correct/run_otter.py, test/test_generate/files/autograder-custom-env/run_otter.py, test/test_generate/files/autograder-r-correct/run_otter.py, test/test_generate/files/autograder-r-requirements-correct/run_otter.py, test/test_generate/files/autograder-token-correct/run_otter.py, test/test_run/files/autograder/source/run_otter.py, test/test_run/test_integration.py
=> Wrap ModuleNotFoundError for otter in run_otter.py

CHANGELOG.md, otter/check/utils.py, otter/check/validate_export/__main__.py
=> Emit a warning instead of an error for text written to stderr while validating submission zips
